// Objeto com as traduções
const translations = {
    pt: {
        // Navegação
        games: "Jogos",
        about: "Sobre",
        news: "Notícias",
        careers: "Carreira",
        store: "Loja",
        coroa: "Coleção",
        // Hero Section
        knowMore: "Saber Mais",
        paradiseTitle: "Paradise",
        paradiseDesc: "Venha criar a história de seu personagem no Paradise!",
        beyweryTitle: "Bey Wery Remastered",
        beyweryDesc: "A premiada franquia de jogos de estratégia retorna com um novo capítulo revolucionário.",
        
        // Jogos em Destaque
        featuredGames: "Jogos em Destaque",
        playNow: "Jogar Agora",
        epicAdventure: "Embarque em uma jornada épica cheia de mistérios e desafios",
        racingEvolution: "Acelere em pistas incríveis e supere seus limites",
        action: "Ação",
        adventure: "Aventura",
        rpg: "RPG",
        racing: "Corrida",
        sport: "Esporte",
        multiplayer: "Multiplayer",
        
        // Notícias
        newsTitle: "NOTÍCIAS",
        readMore: "Leia mais",
        
        // Footer
        contact: "Contato",
        followUs: "Siga-nos",
        allRightsReserved: "Todos os direitos reservados.",
        email: "Email",
        phone: "Telefone",
        
        // Loja
        search: "Buscar",
        categories: "Categorias",
        price: "Preço",
        addToCart: "Adicionar ao Carrinho",
        viewDetails: "Ver Detalhes",
        cart: "Carrinho",
        checkout: "Finalizar Compra",
        emptyCart: "Carrinho Vazio",
        total: "Total",
        all: "Todos",
        clothing: "Vestuário",
        accessories: "Acessórios",
        electronics: "Eletrônicos",
        collectibles: "Colecionáveis",
        books: "Livros",
        newsDate1: "28 de fevereiro de 2025",
        newsDate2: "28 de fevereiro de 2025",
        newsDate3: "28 de fevereiro de 2025",
        newsTitle1: "PGA TOUR® 2K25 Tees Off Worldwide; Disponível agora",
        newsTitle2: "PGA TOUR® 2K25 Tees Off Worldwide; Disponível agora",
        newsTitle3: "PGA TOUR® 2K25 Tees Off Worldwide; Disponível agora",
        newsDate4: "17 de abril de 2025",
        newsDate5: "7 de março de 2025",
        newsDate6: "3 de março de 2025",
        newsTitle4: "Roll Two, Inc. divulgará os resultados do quarto trimestre",
        newsTitle5: "Paradise no WWE® 2K25: Bloodline Edition e Deadman Edition",
        newsTitle6: "Rockstar Games vai adquirir a Video Games Deluxe",
        shirtBlack1: "Camiseta RollTwo Preta\nModelo 1",
        shirtWhite1: "Camiseta RollTwo Branca\nModelo 1",
        shirtBlack2: "Camiseta RollTwo Preta\nModelo 2",
        shirtWhite2: "Camiseta RollTwo Branca\nModelo 2",
        shirtDesc: "Camiseta oficial com logo da RollTwo",
        headset: "Headset Gamer Pro",
        headsetDesc: "Headset profissional com som surround 7.1",
        mouse: "Mouse Gamer RGB",
        mouseDesc: "Mouse profissional com 12000 DPI",
        figure: "Action Figure Paradise",
        figureDesc: "Action Figure exclusiva do jogo Paradise",
        book: "Livro de Aventura",
        bookDesc: "Livro de Aventura exclusivo da RollTwo",
        size: "Tamanho",
        color: "Cor",
        backToTop: "Voltar ao topo",
        home: "Home",
        aboutTitle: "Sobre a RollTwo.inc",
        aboutSlogan: "Holding de tecnologia avançada, protagonista global em experiências digitais imersivas e soluções inovadoras.",
        aboutInnovation: "Inovação no DNA",
        aboutInnovationText1: "Desde sua criação, a RollTwo.inc investe em pesquisa, desenvolvimento e parcerias estratégicas com foco na inovação contínua. A empresa reúne talentos criativos e engenheiros visionários que trabalham juntos para desenvolver produtos e serviços capazes de antecipar tendências e redefinir os padrões do mercado tecnológico.",
        aboutInnovationText2: "Seus principais segmentos incluem:",
        aboutInnovationList1: "Estúdios de games reconhecidos internacionalmente por títulos que combinam narrativa envolvente, jogabilidade avançada e gráficos de última geração;",
        aboutInnovationList2: "Empresas de software dedicadas à criação de plataformas inteligentes, aplicações corporativas e ferramentas baseadas em IA;",
        aboutInnovationList3: "Projetos de hardware e tecnologia imersiva, incluindo realidade aumentada, virtual e dispositivos interativos.",
        aboutHolding: "Uma Holding Estratégica",
        aboutHoldingText: "Como controladora, a RollTwo.inc impulsiona o crescimento das suas subsidiárias por meio de investimentos estruturados, suporte tecnológico e gestão estratégica. Seu modelo operacional é colaborativo, permitindo sinergias entre os negócios para gerar soluções integradas, escaláveis e centradas no usuário.",
        aboutGlobal: "Presença Global, Visão de Futuro",
        aboutGlobalText1: "Com operações e parcerias em diversos países, a RollTwo.inc mantém um olhar voltado para o futuro, investindo em sustentabilidade, segurança digital e impacto social. A empresa acredita que a tecnologia deve ser inclusiva, acessível e usada para construir um mundo mais conectado, criativo e inteligente.",
        aboutGlobalText2: "RollTwo.inc — Tecnologia que move ideias, conecta pessoas e transforma o amanhã.",
        // Copyright/DMCA
        copyrightTitle: "Aviso de Copyright e Política DMCA",
        copyrightIntro: "A RollTwo.inc e as suas subsidiárias, incluindo a UltragameX, Epicnorth Studios e Snowdreams, são detentoras exclusivas dos direitos de autor, marcas registadas, propriedade intelectual, sistemas, mecânicas de jogo, elementos visuais, personagens, narrativas, sons, código-fonte e qualquer outra tecnologia desenvolvida ou licenciada por estas empresas.",
        copyrightRights: "Direitos Reservados",
        copyrightRightsText: "Todo o conteúdo produzido, publicado ou operado pela RollTwo.inc e pelas suas marcas afiliadas está protegido pelas leis de direitos de autor internacionais e por acordos de propriedade intelectual, incluindo, mas não se limitando ao Digital Millennium Copyright Act (DMCA) dos Estados Unidos e demais legislações equivalentes noutras jurisdições.\nÉ estritamente proibida a reprodução, distribuição, modificação, engenharia reversa, comercialização ou qualquer uso não autorizado de:",
        copyrightList1: "Sistemas de gameplay desenvolvidos pelas nossas empresas;",
        copyrightList2: "Layouts, menus e mecânicas exclusivas;",
        copyrightList3: "Roteiros, personagens, bandas sonoras e arte conceptual;",
        copyrightList4: "Códigos-fonte, engines personalizadas ou algoritmos proprietários.",
        copyrightWarning: "A violação de qualquer elemento protegido poderá resultar em ações legais civis e criminais, além de reivindicações formais de remoção de conteúdo (takedown) em plataformas digitais, alojamentos e marketplaces.",
        copyrightDMCA: "Política de DMCA",
        copyrightDMCAIntro: "De acordo com o Digital Millennium Copyright Act (17 U.S.C. § 512), a RollTwo.inc responderá prontamente a denúncias de infração de direitos de autor apresentadas por titulares de direitos ou seus representantes legais.\nSe acredita que qualquer conteúdo publicado por terceiros infringe direitos da RollTwo.inc, siga o procedimento abaixo.",
        copyrightDMCAHow: "Como enviar uma notificação de violação (DMCA Takedown Notice):",
        copyrightDMCAEmail: "Envie um e-mail para: <b>legal@rolltwo.com.br</b> com as seguintes informações:",
        copyrightDMCA1: "A sua identificação completa (nome, empresa, e-mail e telefone).",
        copyrightDMCA2: "Descrição detalhada da obra protegida que alega ter sido violada.",
        copyrightDMCA3: "Link(s) ou identificação clara do conteúdo infrator.",
        copyrightDMCA4: "Declaração de boa-fé de que o uso não é autorizado pelo titular.",
        copyrightDMCA5: "Declaração sob pena de perjúrio de que as informações fornecidas são corretas e de que é o proprietário dos direitos ou está autorizado a agir em nome dele.",
        copyrightDMCA6: "Assinatura eletrónica ou física do titular ou representante legal.",
        copyrightEnforcement: "Aplicação e Reforço",
        copyrightEnforcementText: "A RollTwo.inc reserva-se o direito de tomar medidas legais contra qualquer indivíduo, empresa ou entidade que viole os seus direitos de autor ou tente replicar os seus produtos, sistemas ou experiências interativas sem autorização formal.\nProtegemos a nossa propriedade com rigor — porque a inovação merece respeito.",
        copyrightFooter1: "RollTwo.inc — Todos os direitos reservados.<br>© RollTwo.inc, UltragameX, Epicnorth Studios e Snowdreams.<br>Última atualização: 05/02/2025",
        copyrightFooterShort: "© 2025 RollTwo. Todos os direitos reservados."
    },
    en: {
        // Navigation
        games: "Games",
        about: "About",
        news: "News",
        careers: "Careers",
        store: "Store",
        coroa: "Collection",
        // Hero Section
        knowMore: "Learn More",
        paradiseTitle: "Paradise",
        paradiseDesc: "Come create your character's story in Paradise!",
        beyweryTitle: "Bey Wery Remastered",
        beyweryDesc: "The award-winning strategy game franchise returns with a revolutionary new chapter.",
        
        // Featured Games
        featuredGames: "Featured Games",
        playNow: "Play Now",
        epicAdventure: "Embark on an epic journey full of mysteries and challenges",
        racingEvolution: "Accelerate on amazing tracks and push your limits",
        action: "Action",
        adventure: "Adventure",
        rpg: "RPG",
        racing: "Racing",
        sport: "Sport",
        multiplayer: "Multiplayer",
        
        // News
        newsTitle: "NEWS",
        readMore: "Read more",
        
        // Footer
        contact: "Contact",
        followUs: "Follow Us",
        allRightsReserved: "All rights reserved.",
        email: "Email",
        phone: "Phone",
        
        // Store
        search: "Search",
        categories: "Categories",
        price: "Price",
        addToCart: "Add to Cart",
        viewDetails: "View Details",
        cart: "Cart",
        checkout: "Checkout",
        emptyCart: "Empty Cart",
        total: "Total",
        all: "All",
        clothing: "Clothing",
        accessories: "Accessories",
        electronics: "Electronics",
        collectibles: "Collectibles",
        books: "Books",
        newsDate1: "February 28, 2025",
        newsDate2: "February 28, 2025",
        newsDate3: "February 28, 2025",
        newsTitle1: "PGA TOUR® 2K25 Tees Off Worldwide; Available now",
        newsTitle2: "PGA TOUR® 2K25 Tees Off Worldwide; Available now",
        newsTitle3: "PGA TOUR® 2K25 Tees Off Worldwide; Available now",
        newsDate4: "April 17, 2025",
        newsDate5: "March 7, 2025",
        newsDate6: "March 3, 2025",
        newsTitle4: "Roll Two, Inc. will announce Q4 results",
        newsTitle5: "Paradise in WWE® 2K25: Bloodline Edition and Deadman Edition",
        newsTitle6: "Rockstar Games to acquire Video Games Deluxe",
        shirtBlack1: "RollTwo Black T-shirt\nModel 1",
        shirtWhite1: "RollTwo White T-shirt\nModel 1",
        shirtBlack2: "RollTwo Black T-shirt\nModel 2",
        shirtWhite2: "RollTwo White T-shirt\nModel 2",
        shirtDesc: "Official t-shirt with RollTwo logo",
        headset: "Pro Gaming Headset",
        headsetDesc: "Professional headset with 7.1 surround sound",
        mouse: "RGB Gaming Mouse",
        mouseDesc: "Professional mouse with 12000 DPI",
        figure: "Paradise Action Figure",
        figureDesc: "Exclusive Paradise game action figure",
        book: "Adventure Book",
        bookDesc: "Exclusive RollTwo Adventure Book",
        size: "Size",
        color: "Color",
        backToTop: "Back to top",
        home: "Home",
        aboutTitle: "About RollTwo.inc",
        aboutSlogan: "Advanced technology holding, global leader in immersive digital experiences and innovative solutions.",
        aboutInnovation: "Innovation in Our DNA",
        aboutInnovationText1: "Since its creation, RollTwo.inc has invested in research, development, and strategic partnerships focused on continuous innovation. The company brings together creative talents and visionary engineers who work together to develop products and services capable of anticipating trends and redefining the standards of the technology market.",
        aboutInnovationText2: "Its main segments include:",
        aboutInnovationList1: "Game studios internationally recognized for titles that combine engaging storytelling, advanced gameplay, and cutting-edge graphics;",
        aboutInnovationList2: "Software companies dedicated to creating intelligent platforms, corporate applications, and AI-based tools;",
        aboutInnovationList3: "Hardware and immersive technology projects, including augmented reality, virtual reality, and interactive devices.",
        aboutHolding: "A Strategic Holding",
        aboutHoldingText: "As a parent company, RollTwo.inc drives the growth of its subsidiaries through structured investments, technological support, and strategic management. Its operational model is collaborative, allowing synergies between businesses to generate integrated, scalable, and user-centered solutions.",
        aboutGlobal: "Global Presence, Future Vision",
        aboutGlobalText1: "With operations and partnerships in several countries, RollTwo.inc keeps an eye on the future, investing in sustainability, digital security, and social impact. The company believes that technology should be inclusive, accessible, and used to build a more connected, creative, and intelligent world.",
        aboutGlobalText2: "RollTwo.inc — Technology that moves ideas, connects people, and transforms tomorrow.",
        // Copyright/DMCA
        copyrightTitle: "Copyright Notice and DMCA Policy",
        copyrightIntro: "RollTwo.inc and its subsidiaries, including UltragameX, Epicnorth Studios, and Snowdreams, are the exclusive holders of copyrights, trademarks, intellectual property, systems, game mechanics, visual elements, characters, narratives, sounds, source code, and any other technology developed or licensed by these companies.",
        copyrightRights: "All Rights Reserved",
        copyrightRightsText: "All content produced, published, or operated by RollTwo.inc and its affiliated brands is protected by international copyright laws and intellectual property agreements, including but not limited to the United States Digital Millennium Copyright Act (DMCA) and equivalent legislation in other jurisdictions.\nIt is strictly prohibited to reproduce, distribute, modify, reverse engineer, commercialize, or make any unauthorized use of:",
        copyrightList1: "Gameplay systems developed by our companies;",
        copyrightList2: "Exclusive layouts, menus, and mechanics;",
        copyrightList3: "Scripts, characters, soundtracks, and concept art;",
        copyrightList4: "Source code, custom engines, or proprietary algorithms.",
        copyrightWarning: "Violation of any protected element may result in civil and criminal legal actions, as well as formal takedown claims on digital platforms, hosting, and marketplaces.",
        copyrightDMCA: "DMCA Policy",
        copyrightDMCAIntro: "In accordance with the Digital Millennium Copyright Act (17 U.S.C. § 512), RollTwo.inc will promptly respond to copyright infringement complaints submitted by rights holders or their legal representatives.\nIf you believe that any content published by third parties infringes the rights of RollTwo.inc, follow the procedure below.",
        copyrightDMCAHow: "How to send a takedown notice (DMCA Takedown Notice):",
        copyrightDMCAEmail: "Send an email to: <b>legal@rolltwo.com.br</b> with the following information:",
        copyrightDMCA1: "Your full identification (name, company, email, and phone).",
        copyrightDMCA2: "Detailed description of the protected work you claim has been infringed.",
        copyrightDMCA3: "Link(s) or clear identification of the infringing content.",
        copyrightDMCA4: "Good faith statement that the use is not authorized by the rights holder.",
        copyrightDMCA5: "Statement under penalty of perjury that the information provided is correct and that you are the rights holder or authorized to act on their behalf.",
        copyrightDMCA6: "Electronic or physical signature of the rights holder or legal representative.",
        copyrightEnforcement: "Enforcement",
        copyrightEnforcementText: "RollTwo.inc reserves the right to take legal action against any individual, company, or entity that violates its copyrights or attempts to replicate its products, systems, or interactive experiences without formal authorization.\nWe rigorously protect our property — because innovation deserves respect.",
        copyrightFooter1: "RollTwo.inc — All rights reserved.<br>© RollTwo.inc, UltragameX, Epicnorth Studios and Snowdreams.<br>Last update: 02/05/2025",
        copyrightFooterShort: "© 2025 RollTwo. All rights reserved."
    },
    es: {
        // Navegación
        games: "Juegos",
        about: "Acerca de",
        news: "Noticias",
        careers: "Carreras",
        store: "Tienda",
        coroa: "Colección",
        // Sección Hero
        knowMore: "Saber Más",
        paradiseTitle: "Paradise",
        paradiseDesc: "¡Ven a crear la historia de tu personaje en Paradise!",
        beyweryTitle: "Bey Wery Remastered",
        beyweryDesc: "La galardonada franquicia de juegos de estrategia regresa con un nuevo capítulo revolucionario.",
        
        // Juegos Destacados
        featuredGames: "Juegos Destacados",
        playNow: "Jugar Ahora",
        epicAdventure: "Embárcate en un viaje épico lleno de misterios y desafíos",
        racingEvolution: "Acelera en pistas increíbles y supera tus límites",
        action: "Acción",
        adventure: "Aventura",
        rpg: "RPG",
        racing: "Carreras",
        sport: "Deportes",
        multiplayer: "Multijugador",
        
        // Noticias
        newsTitle: "NOTICIAS",
        readMore: "Leer más",
        
        // Pie de página
        contact: "Contacto",
        followUs: "Síguenos",
        allRightsReserved: "Todos los derechos reservados.",
        email: "Correo",
        phone: "Teléfono",
        
        // Tienda
        search: "Buscar",
        categories: "Categorías",
        price: "Precio",
        addToCart: "Añadir al Carrito",
        viewDetails: "Ver Detalles",
        cart: "Carrito",
        checkout: "Finalizar Compra",
        emptyCart: "Carrito Vacío",
        total: "Total",
        all: "Todos",
        clothing: "Ropa",
        accessories: "Accesorios",
        electronics: "Electrónicos",
        collectibles: "Coleccionables",
        books: "Libros",
        newsDate1: "28 de febrero de 2025",
        newsDate2: "28 de febrero de 2025",
        newsDate3: "28 de febrero de 2025",
        newsTitle1: "PGA TOUR® 2K25 Tees Off Worldwide; Disponible ahora",
        newsTitle2: "PGA TOUR® 2K25 Tees Off Worldwide; Disponible ahora",
        newsTitle3: "PGA TOUR® 2K25 Tees Off Worldwide; Disponible ahora",
        newsDate4: "17 de abril de 2025",
        newsDate5: "7 de marzo de 2025",
        newsDate6: "3 de marzo de 2025",
        newsTitle4: "Roll Two, Inc. publicará los resultados del cuarto trimestre",
        newsTitle5: "Paradise en WWE® 2K25: Bloodline Edition y Deadman Edition",
        newsTitle6: "Rockstar Games adquirirá Video Games Deluxe",
        shirtBlack1: "Camiseta RollTwo Negra\nModelo 1",
        shirtWhite1: "Camiseta RollTwo Blanca\nModelo 1",
        shirtBlack2: "Camiseta RollTwo Negra\nModelo 2",
        shirtWhite2: "Camiseta RollTwo Blanca\nModelo 2",
        shirtDesc: "Camiseta oficial con logo de RollTwo",
        headset: "Auriculares Gamer Pro",
        headsetDesc: "Auriculares profesionales con sonido envolvente 7.1",
        mouse: "Ratón Gamer RGB",
        mouseDesc: "Ratón profesional con 12000 DPI",
        figure: "Figura de Acción Paradise",
        figureDesc: "Figura exclusiva del juego Paradise",
        book: "Libro de Aventura",
        bookDesc: "Libro de Aventura exclusivo de RollTwo",
        size: "Talla",
        color: "Color",
        backToTop: "Volver arriba",
        home: "Inicio",
        aboutTitle: "Sobre RollTwo.inc",
        aboutSlogan: "Holding de tecnología avanzada, protagonista global en experiencias digitales inmersivas y soluciones innovadoras.",
        aboutInnovation: "Innovación en el ADN",
        aboutInnovationText1: "Desde su creación, RollTwo.inc invierte en investigación, desarrollo y alianzas estratégicas con foco en la innovación continua. La empresa reúne talentos creativos e ingenieros visionarios que trabajan juntos para desarrollar productos y servicios capaces de anticipar tendencias y redefinir los estándares del mercado tecnológico.",
        aboutInnovationText2: "Sus principales segmentos incluyen:",
        aboutInnovationList1: "Estudios de juegos reconocidos internacionalmente por títulos que combinan narrativa envolvente, jugabilidad avanzada y gráficos de última generación;",
        aboutInnovationList2: "Empresas de software dedicadas a la creación de plataformas inteligentes, aplicaciones corporativas y herramientas basadas en IA;",
        aboutInnovationList3: "Proyectos de hardware y tecnología inmersiva, incluyendo realidad aumentada, virtual y dispositivos interactivos.",
        aboutHolding: "Una Holding Estratégica",
        aboutHoldingText: "Como controladora, RollTwo.inc impulsa el crecimiento de sus subsidiarias mediante inversiones estructuradas, soporte tecnológico y gestión estratégica. Su modelo operativo es colaborativo, permitiendo sinergias entre los negocios para generar soluciones integradas, escalables y centradas en el usuario.",
        aboutGlobal: "Presencia Global, Visión de Futuro",
        aboutGlobalText1: "Con operaciones y alianzas en varios países, RollTwo.inc mantiene la mirada puesta en el futuro, invirtiendo en sostenibilidad, seguridad digital e impacto social. La empresa cree que la tecnología debe ser inclusiva, accesible y utilizada para construir un mundo más conectado, creativo e inteligente.",
        aboutGlobalText2: "RollTwo.inc — Tecnología que mueve ideas, conecta personas y transforma el mañana.",
        // Copyright/DMCA
        copyrightTitle: "Aviso de Copyright y Política DMCA",
        copyrightIntro: "RollTwo.inc y sus subsidiarias, incluidas UltragameX, Epicnorth Studios y Snowdreams, son titulares exclusivos de los derechos de autor, marcas registradas, propiedad intelectual, sistemas, mecánicas de juego, elementos visuales, personajes, narrativas, sonidos, código fuente y cualquier otra tecnología desarrollada o licenciada por estas empresas.",
        copyrightRights: "Derechos Reservados",
        copyrightRightsText: "Todo el contenido producido, publicado u operado por RollTwo.inc y sus marcas afiliadas está protegido por las leyes internacionales de derechos de autor y acuerdos de propiedad intelectual, incluyendo, pero no limitado a, la Digital Millennium Copyright Act (DMCA) de los Estados Unidos y demás legislaciones equivalentes en otras jurisdicciones.\nEstá estrictamente prohibida la reproducción, distribución, modificación, ingeniería inversa, comercialización o cualquier uso no autorizado de:",
        copyrightList1: "Sistemas de juego desarrollados por nuestras empresas;",
        copyrightList2: "Diseños, menús y mecánicas exclusivas;",
        copyrightList3: "Guiones, personajes, bandas sonoras y arte conceptual;",
        copyrightList4: "Código fuente, motores personalizados o algoritmos propietarios.",
        copyrightWarning: "La violación de cualquier elemento protegido puede resultar en acciones legales civiles y penales, además de reclamaciones formales de eliminación de contenido (takedown) en plataformas digitales, alojamientos y marketplaces.",
        copyrightDMCA: "Política de DMCA",
        copyrightDMCAIntro: "De acuerdo con la Digital Millennium Copyright Act (17 U.S.C. § 512), RollTwo.inc responderá prontamente a denuncias de infracción de derechos de autor presentadas por titulares de derechos o sus representantes legales.\nSi cree que algún contenido publicado por terceros infringe los derechos de RollTwo.inc, siga el procedimiento a continuación.",
        copyrightDMCAHow: "Cómo enviar una notificación de infracción (DMCA Takedown Notice):",
        copyrightDMCAEmail: "Envíe un correo electrónico a: <b>legal@rolltwo.com.br</b> con la siguiente información:",
        copyrightDMCA1: "Su identificación completa (nombre, empresa, correo electrónico y teléfono).",
        copyrightDMCA2: "Descripción detallada de la obra protegida que alega ha sido infringida.",
        copyrightDMCA3: "Enlace(s) o identificación clara del contenido infractor.",
        copyrightDMCA4: "Declaración de buena fe de que el uso no está autorizado por el titular.",
        copyrightDMCA5: "Declaración bajo pena de perjurio de que la información proporcionada es correcta y que usted es el titular de los derechos o está autorizado para actuar en su nombre.",
        copyrightDMCA6: "Firma electrónica o física del titular o representante legal.",
        copyrightEnforcement: "Aplicación y Refuerzo",
        copyrightEnforcementText: "RollTwo.inc se reserva el derecho de tomar medidas legales contra cualquier individuo, empresa o entidad que viole sus derechos de autor o intente replicar sus productos, sistemas o experiencias interactivas sin autorización formal.\nProtegemos nuestra propiedad con rigor — porque la innovación merece respeto.",
        copyrightFooter1: "RollTwo.inc — Todos los derechos reservados.<br>© RollTwo.inc, UltragameX, Epicnorth Studios y Snowdreams.<br>Última actualización: 05/02/2025",
        copyrightFooterShort: "© 2025 RollTwo. Todos los derechos reservados."
    },
    zh: {
        games: "游戏",
        about: "关于",
        news: "新闻",
        careers: "招聘",
        store: "商店",
        coroa: "收藏",
        knowMore: "了解更多",
        paradiseTitle: "天堂",
        paradiseDesc: "来创造你在天堂的角色故事吧！",
        beyweryTitle: "Bey Wery 重制版",
        beyweryDesc: "屡获殊荣的策略游戏系列带来革命性新篇章。",
        featuredGames: "精选游戏",
        playNow: "立即游玩",
        epicAdventure: "踏上充满神秘和挑战的史诗之旅",
        racingEvolution: "在精彩赛道上加速，突破极限",
        action: "动作",
        adventure: "冒险",
        rpg: "角色扮演",
        racing: "竞速",
        sport: "体育",
        multiplayer: "多人",
        newsTitle: "新闻",
        readMore: "阅读更多",
        contact: "联系",
        followUs: "关注我们",
        allRightsReserved: "保留所有权利。",
        email: "邮箱",
        phone: "电话",
        search: "搜索",
        categories: "分类",
        price: "价格",
        addToCart: "加入购物车",
        viewDetails: "查看详情",
        cart: "购物车",
        checkout: "结账",
        emptyCart: "购物车为空",
        total: "总计",
        all: "全部",
        clothing: "服装",
        accessories: "配件",
        electronics: "电子产品",
        collectibles: "收藏品",
        books: "书籍",
        newsDate1: "2025年2月28日",
        newsDate2: "2025年2月28日",
        newsDate3: "2025年2月28日",
        newsTitle1: "PGA TOUR® 2K25 全球发售；现已上市",
        newsTitle2: "PGA TOUR® 2K25 全球发售；现已上市",
        newsTitle3: "PGA TOUR® 2K25 全球发售；现已上市",
        newsDate4: "2025年4月17日",
        newsDate5: "2025年3月7日",
        newsDate6: "2025年3月3日",
        newsTitle4: "Roll Two, Inc. 公布第四季度业绩",
        newsTitle5: "Paradise 登陆 WWE® 2K25: Bloodline Edition 和 Deadman Edition",
        newsTitle6: "Rockstar Games 将收购 Video Games Deluxe",
        shirtBlack1: "RollTwo 黑色T恤\n款式1",
        shirtWhite1: "RollTwo 白色T恤\n款式1",
        shirtBlack2: "RollTwo 黑色T恤\n款式2",
        shirtWhite2: "RollTwo 白色T恤\n款式2",
        shirtDesc: "RollTwo官方标志T恤",
        headset: "专业游戏耳机",
        headsetDesc: "7.1环绕声专业耳机",
        mouse: "RGB游戏鼠标",
        mouseDesc: "12000 DPI专业鼠标",
        figure: "Paradise手办",
        figureDesc: "Paradise游戏独家手办",
        book: "冒险书籍",
        bookDesc: "RollTwo独家冒险书籍",
        size: "尺码",
        color: "颜色",
        backToTop: "返回顶部",
        home: "首页",
        aboutTitle: "关于 RollTwo.inc",
        aboutSlogan: "先进科技控股公司，全球沉浸式数字体验和创新解决方案的引领者。",
        aboutInnovation: "创新基因",
        aboutInnovationText1: "自成立以来，RollTwo.inc 一直专注于研发、创新和战略合作。公司汇聚了创意人才和有远见的工程师，共同开发能够引领趋势、重塑科技市场标准的产品和服务。",
        aboutInnovationText2: "其主要领域包括：",
        aboutInnovationList1: "国际知名游戏工作室，作品兼具引人入胜的叙事、先进玩法和顶级画面；",
        aboutInnovationList2: "专注于智能平台、企业应用和AI工具开发的软件公司；",
        aboutInnovationList3: "硬件与沉浸式科技项目，包括增强现实、虚拟现实和交互设备。",
        aboutHolding: "战略控股公司",
        aboutHoldingText: "作为控股公司，RollTwo.inc 通过结构化投资、技术支持和战略管理推动子公司成长。其协作型运营模式促进业务协同，打造集成、可扩展、以用户为中心的解决方案。",
        aboutGlobal: "全球布局，未来愿景",
        aboutGlobalText1: "RollTwo.inc 在多个国家开展业务与合作，关注未来，投资于可持续发展、数字安全和社会影响。公司相信科技应当包容、易用，用于建设更互联、更具创造力和智能的世界。",
        aboutGlobalText2: "RollTwo.inc — 推动创意、连接人群、改变未来的科技。",
        // Copyright/DMCA
        copyrightTitle: "版权声明与DMCA政策",
        copyrightIntro: "RollTwo.inc及其子公司，包括UltragameX、Epicnorth Studios和Snowdreams，拥有所有版权、商标、知识产权、系统、游戏机制、视觉元素、角色、叙事、声音、源代码及由这些公司开发或授权的任何其他技术的专有权。",
        copyrightRights: "版权所有",
        copyrightRightsText: "RollTwo.inc及其附属品牌生产、发布或运营的所有内容均受国际版权法和知识产权协议保护，包括但不限于美国《数字千年版权法案》（DMCA）及其他司法管辖区的相关法律。\n严禁未经授权复制、分发、修改、逆向工程、商业化或以其他方式使用：",
        copyrightList1: "由我们公司开发的游戏系统；",
        copyrightList2: "专属布局、菜单和机制；",
        copyrightList3: "剧本、角色、配乐和概念艺术；",
        copyrightList4: "源代码、自定义引擎或专有算法。",
        copyrightWarning: "任何受保护元素的侵权行为都可能导致民事和刑事法律诉讼，以及在数字平台、主机和市场上的正式下架请求。",
        copyrightDMCA: "DMCA政策",
        copyrightDMCAIntro: "根据《数字千年版权法案》（17 U.S.C. § 512），RollTwo.inc将及时响应权利人或其法律代表提出的版权侵权投诉。\n如果您认为第三方发布的任何内容侵犯了RollTwo.inc的权利，请按照以下程序操作。",
        copyrightDMCAHow: "如何发送侵权通知（DMCA Takedown Notice）：",
        copyrightDMCAEmail: "请发送电子邮件至：<b>legal@rolltwo.com.br</b>，并提供以下信息：",
        copyrightDMCA1: "您的完整身份信息（姓名、公司、电子邮件和电话）。",
        copyrightDMCA2: "您声称被侵权的受保护作品的详细描述。",
        copyrightDMCA3: "侵权内容的链接或明确标识。",
        copyrightDMCA4: "善意声明该使用未经权利人授权。",
        copyrightDMCA5: "在伪证罪处罚下声明所提供信息正确，并且您是权利人或被授权代表其行事。",
        copyrightDMCA6: "权利人或法律代表的电子或实体签名。",
        copyrightEnforcement: "执行与维权",
        copyrightEnforcementText: "RollTwo.inc保留对任何侵犯其版权或试图在未经正式授权的情况下复制其产品、系统或互动体验的个人、公司或实体采取法律行动的权利。\n我们严格保护我们的财产——因为创新值得尊重。",
        copyrightFooter1: "RollTwo.inc — 保留所有权利。<br>© RollTwo.inc, UltragameX, Epicnorth Studios 和 Snowdreams.<br>最后更新：2025年02月05日",
        copyrightFooterShort: "© 2025 RollTwo. 保留所有权利。"
    },
    "pt-pt": {
        games: "Jogos",
        about: "Sobre",
        news: "Notícias",
        careers: "Carreiras",
        store: "Loja",
        knowMore: "Saber Mais",
        paradiseTitle: "Paradise",
        paradiseDesc: "Venha criar a história da sua personagem no Paradise!",
        beyweryTitle: "Bey Wery Remastered",
        beyweryDesc: "A premiada série de jogos de estratégia regressa com um novo capítulo revolucionário.",
        featuredGames: "Jogos em Destaque",
        playNow: "Jogar Agora",
        epicAdventure: "Embarca numa jornada épica cheia de mistérios e desafios",
        racingEvolution: "Acelera em pistas incríveis e supera os teus limites",
        action: "Ação",
        adventure: "Aventura",
        rpg: "RPG",
        racing: "Corrida",
        sport: "Desporto",
        multiplayer: "Multijogador",
        newsTitle: "NOTÍCIAS",
        readMore: "Ler mais",
        contact: "Contacto",
        followUs: "Segue-nos",
        allRightsReserved: "Todos os direitos reservados.",
        email: "Email",
        phone: "Telefone",
        search: "Procurar",
        categories: "Categorias",
        price: "Preço",
        addToCart: "Adicionar ao Carrinho",
        viewDetails: "Ver Detalhes",
        cart: "Carrinho",
        checkout: "Finalizar Compra",
        emptyCart: "Carrinho Vazio",
        total: "Total",
        all: "Todos",
        clothing: "Vestuário",
        accessories: "Acessórios",
        electronics: "Eletrónica",
        collectibles: "Colecionáveis",
        books: "Livros",
        newsDate1: "28 de fevereiro de 2025",
        newsDate2: "28 de fevereiro de 2025",
        newsDate3: "28 de fevereiro de 2025",
        newsTitle1: "PGA TOUR® 2K25 Tees Off Worldwide; Disponível agora",
        newsTitle2: "PGA TOUR® 2K25 Tees Off Worldwide; Disponível agora",
        newsTitle3: "PGA TOUR® 2K25 Tees Off Worldwide; Disponível agora",
        newsDate4: "17 de abril de 2025",
        newsDate5: "7 de março de 2025",
        newsDate6: "3 de março de 2025",
        newsTitle4: "Roll Two, Inc. divulgará os resultados do quarto trimestre",
        newsTitle5: "Paradise no WWE® 2K25: Bloodline Edition e Deadman Edition",
        newsTitle6: "Rockstar Games vai adquirir a Video Games Deluxe",
        shirtBlack1: "Camisola RollTwo Preta\nModelo 1",
        shirtWhite1: "Camisola RollTwo Branca\nModelo 1",
        shirtBlack2: "Camisola RollTwo Preta\nModelo 2",
        shirtWhite2: "Camisola RollTwo Branca\nModelo 2",
        shirtDesc: "Camisola oficial com logótipo da RollTwo",
        headset: "Headset Gamer Pro",
        headsetDesc: "Headset profissional com som surround 7.1",
        mouse: "Rato Gamer RGB",
        mouseDesc: "Rato profissional com 12000 DPI",
        figure: "Action Figure Paradise",
        figureDesc: "Action Figure exclusiva do jogo Paradise",
        book: "Livro de Aventura",
        bookDesc: "Livro de Aventura exclusivo da RollTwo",
        size: "Tamanho",
        color: "Cor",
        backToTop: "Voltar ao topo",
        home: "Início",
        aboutTitle: "Sobre a RollTwo.inc",
        aboutSlogan: "Holding de tecnologia avançada, protagonista global em experiências digitais imersivas e soluções inovadoras.",
        aboutInnovation: "Inovação no ADN",
        aboutInnovationText1: "Desde a sua criação, a RollTwo.inc investe em investigação, desenvolvimento e parcerias estratégicas com foco na inovação contínua. A empresa reúne talentos criativos e engenheiros visionários que trabalham juntos para desenvolver produtos e serviços capazes de antecipar tendências e redefinir os padrões do mercado tecnológico.",
        aboutInnovationText2: "Os seus principais segmentos incluem:",
        aboutInnovationList1: "Estúdios de jogos reconhecidos internacionalmente por títulos que combinam narrativa envolvente, jogabilidade avançada e gráficos de última geração;",
        aboutInnovationList2: "Empresas de software dedicadas à criação de plataformas inteligentes, aplicações corporativas e ferramentas baseadas em IA;",
        aboutInnovationList3: "Projetos de hardware e tecnologia imersiva, incluindo realidade aumentada, virtual e dispositivos interativos.",
        aboutHolding: "Uma Holding Estratégica",
        aboutHoldingText: "Como controladora, a RollTwo.inc impulsiona o crescimento das suas subsidiárias por meio de investimentos estruturados, suporte tecnológico e gestão estratégica. O seu modelo operacional é colaborativo, permitindo sinergias entre os negócios para gerar soluções integradas, escaláveis e centradas no utilizador.",
        aboutGlobal: "Presença Global, Visão de Futuro",
        aboutGlobalText1: "Com operações e parcerias em diversos países, a RollTwo.inc mantém um olhar voltado para o futuro, investindo em sustentabilidade, segurança digital e impacto social. A empresa acredita que a tecnologia deve ser inclusiva, acessível e usada para construir um mundo mais conectado, criativo e inteligente.",
        aboutGlobalText2: "RollTwo.inc — Tecnologia que move ideias, conecta pessoas e transforma o amanhã.",
        // Copyright/DMCA
        copyrightTitle: "Aviso de Copyright e Política DMCA",
        copyrightIntro: "A RollTwo.inc e as suas subsidiárias, incluindo a UltragameX, Epicnorth Studios e Snowdreams, são detentoras exclusivas dos direitos de autor, marcas registadas, propriedade intelectual, sistemas, mecânicas de jogo, elementos visuais, personagens, narrativas, sons, código-fonte e qualquer outra tecnologia desenvolvida ou licenciada por estas empresas.",
        copyrightRights: "Direitos Reservados",
        copyrightRightsText: "Todo o conteúdo produzido, publicado ou operado pela RollTwo.inc e pelas suas marcas afiliadas está protegido pelas leis de direitos de autor internacionais e por acordos de propriedade intelectual, incluindo, mas não se limitando ao Digital Millennium Copyright Act (DMCA) dos Estados Unidos e demais legislações equivalentes noutras jurisdições.\nÉ estritamente proibida a reprodução, distribuição, modificação, engenharia reversa, comercialização ou qualquer uso não autorizado de:",
        copyrightList1: "Sistemas de gameplay desenvolvidos pelas nossas empresas;",
        copyrightList2: "Layouts, menus e mecânicas exclusivas;",
        copyrightList3: "Roteiros, personagens, bandas sonoras e arte conceptual;",
        copyrightList4: "Códigos-fonte, engines personalizadas ou algoritmos proprietários.",
        copyrightWarning: "A violação de qualquer elemento protegido poderá resultar em ações legais civis e criminais, além de reivindicações formais de remoção de conteúdo (takedown) em plataformas digitais, alojamentos e marketplaces.",
        copyrightDMCA: "Política de DMCA",
        copyrightDMCAIntro: "De acordo com o Digital Millennium Copyright Act (17 U.S.C. § 512), a RollTwo.inc responderá prontamente a denúncias de infração de direitos de autor apresentadas por titulares de direitos ou seus representantes legais.\nSe acredita que qualquer conteúdo publicado por terceiros infringe direitos da RollTwo.inc, siga o procedimento abaixo.",
        copyrightDMCAHow: "Como enviar uma notificação de violação (DMCA Takedown Notice):",
        copyrightDMCAEmail: "Envie um e-mail para: <b>legal@rolltwo.com.br</b> com as seguintes informações:",
        copyrightDMCA1: "A sua identificação completa (nome, empresa, e-mail e telefone).",
        copyrightDMCA2: "Descrição detalhada da obra protegida que alega ter sido violada.",
        copyrightDMCA3: "Link(s) ou identificação clara do conteúdo infrator.",
        copyrightDMCA4: "Declaração de boa-fé de que o uso não é autorizado pelo titular.",
        copyrightDMCA5: "Declaração sob pena de perjúrio de que as informações fornecidas são corretas e de que é o proprietário dos direitos ou está autorizado a agir em nome dele.",
        copyrightDMCA6: "Assinatura eletrónica ou física do titular ou representante legal.",
        copyrightEnforcement: "Aplicação e Reforço",
        copyrightEnforcementText: "A RollTwo.inc reserva-se o direito de tomar medidas legais contra qualquer indivíduo, empresa ou entidade que viole os seus direitos de autor ou tente replicar os seus produtos, sistemas ou experiências interativas sem autorização formal.\nProtegemos a nossa propriedade com rigor — porque a inovação merece respeito.",
        copyrightFooter1: "RollTwo.inc — Todos os direitos reservados.<br>© RollTwo.inc, UltragameX, Epicnorth Studios e Snowdreams.<br>Última atualização: 05/02/2025",
        copyrightFooterShort: "© 2025 RollTwo. Todos os direitos reservados."
    }
};

// Função para atualizar o texto da página
function updateLanguage(lang) {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    
    // Salvar preferência de idioma
    localStorage.setItem('preferredLanguage', lang);
    
    // Atualizar o atributo lang do HTML
    document.documentElement.lang = lang;
}

// Inicialização
document.addEventListener('DOMContentLoaded', () => {
    const languageToggle = document.getElementById('language-toggle');
    const languageDropdown = document.querySelector('.language-dropdown');
    const languageLinks = document.querySelectorAll('.language-dropdown a');
    
    // Carregar idioma salvo ou usar padrão
    const savedLanguage = localStorage.getItem('preferredLanguage') || 'pt';
    updateLanguage(savedLanguage);
    
    // Toggle do dropdown
    languageToggle.addEventListener('click', (e) => {
        e.stopPropagation();
        languageDropdown.classList.toggle('show');
    });
    
    // Fechar dropdown ao clicar fora (reforçado)
    document.addEventListener('click', (e) => {
        setTimeout(() => {
            if (!languageToggle.contains(e.target) && !languageDropdown.contains(e.target)) {
                languageDropdown.classList.remove('show');
            }
        }, 50);
    });

    // Fechar dropdown ao clicar em um link (reforçado)
    languageLinks.forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            const lang = link.getAttribute('data-lang');
            updateLanguage(lang);
            setTimeout(() => {
                languageDropdown.classList.remove('show');
            }, 50);
        });
    });

    // Prevenir que o clique no dropdown feche o menu
    languageDropdown.addEventListener('click', (e) => {
        e.stopPropagation();
    });
}); 